const TRADE_ALIASES = {
  electrician: "Electrical",
  electrical: "Electrical",
  electric: "Electrical",
  elec: "Electrical",
  power: "Electrical",
  lighting: "Electrical",
  lowvoltage: "Electrical",
  "low voltage": "Electrical",
  data: "Electrical",
  telecom: "Electrical",
  firealarm: "Electrical",
  "fire alarm": "Electrical",

  plumber: "Plumbing",
  plumbing: "Plumbing",
  plumb: "Plumbing",
  pipefitter: "Plumbing",
  piping: "Plumbing",
  gasfitter: "Plumbing",
  gas: "Plumbing",

  framer: "Framing",
  framing: "Framing",
  woodframing: "Framing",
  "wood framing": "Framing",
  carpenter: "Carpentry",
  carpentry: "Carpentry",
  finishcarpenter: "Carpentry",
  "finish carpenter": "Carpentry",
  trimcarpenter: "Carpentry",
  "trim carpenter": "Carpentry",

  drywaller: "Drywall",
  drywall: "Drywall",
  "drywall crew": "Drywall",
  boarder: "Drywall",
  taper: "Drywall",
  taping: "Drywall",
  mudding: "Drywall",

  painter: "Painting",
  painting: "Painting",
  paint: "Painting",
  coatings: "Painting",

  insulation: "Insulation",
  insulator: "Insulation",
  sprayfoam: "Insulation",
  "spray foam": "Insulation",
  battinsulation: "Insulation",
  "batt insulation": "Insulation",

  hvac: "HVAC",
  mechanical: "Mechanical",
  sheetmetal: "HVAC",
  "sheet metal": "HVAC",
  ductwork: "HVAC",
  duct: "HVAC",
  ventilation: "HVAC",
  heating: "HVAC",
  cooling: "HVAC",

  concrete: "Concrete",
  formwork: "Concrete",
  forming: "Concrete",
  foundation: "Concrete",
  foundations: "Concrete",
  rebar: "Concrete",
  placing: "Concrete",
  finisher: "Concrete",
  flatwork: "Concrete",

  roofer: "Roofing",
  roofing: "Roofing",
  roof: "Roofing",
  waterproofer: "Waterproofing",
  waterproofing: "Waterproofing",
  dampproofing: "Waterproofing",
  "building envelope": "Envelope",
  envelope: "Envelope",
  cladding: "Envelope",
  siding: "Envelope",

  flooring: "Flooring",
  floorer: "Flooring",
  tile: "Tile",
  tiling: "Tile",
  tiler: "Tile",
  carpet: "Flooring",
  vinyl: "Flooring",
  lvt: "Flooring",
  laminate: "Flooring",
  hardwood: "Flooring",

  cabinet: "Cabinets",
  cabinets: "Cabinets",
  cabinetry: "Cabinets",
  millwork: "Millwork",
  casework: "Millwork",
  countertop: "Countertops",
  countertops: "Countertops",
  stone: "Countertops",

  glazing: "Glazing",
  glazier: "Glazing",
  glass: "Glazing",
  windows: "Glazing",
  window: "Glazing",
  storefront: "Glazing",

  steel: "Steel",
  structuralsteel: "Steel",
  "structural steel": "Steel",
  metals: "Steel",
  miscmetals: "Steel",
  "misc metals": "Steel",
  stairs: "Steel",
  railings: "Steel",
  railing: "Steel",

  demolition: "Demolition",
  demo: "Demolition",
  abatement: "Abatement",
  asbestos: "Abatement",

  excavation: "Excavation",
  excavator: "Excavation",
  earthworks: "Excavation",
  shoring: "Excavation",
  civil: "Civil",
  sitework: "Civil",
  "site work": "Civil",
  paving: "Civil",
  asphalt: "Civil",
  landscaping: "Landscaping",
  landscape: "Landscaping",
  irrigation: "Landscaping",

  masonry: "Masonry",
  mason: "Masonry",
  brick: "Masonry",
  block: "Masonry",
  bricklaying: "Masonry",

  doors: "Doors and Hardware",
  door: "Doors and Hardware",
  hardware: "Doors and Hardware",
  locksmith: "Doors and Hardware",
  accesscontrol: "Security",
  "access control": "Security",
  security: "Security",
  cctv: "Security",

  firestopping: "Firestopping",
  "fire stopping": "Firestopping",
  fireproofing: "Fireproofing",
  sprayfireproofing: "Fireproofing",
  "spray fireproofing": "Fireproofing",
  sprinkler: "Fire Protection",
  sprinklers: "Fire Protection",
  sprinklerfitter: "Fire Protection",
  "sprinkler fitter": "Fire Protection",
  fireprotection: "Fire Protection",
  "fire protection": "Fire Protection",

  elevator: "Elevator",
  elevators: "Elevator",
  lift: "Elevator",

  cleaning: "Cleaning",
  cleaner: "Cleaning",
  finalclean: "Cleaning",
  "final clean": "Cleaning",
  waste: "Waste Removal",
  garbage: "Waste Removal",
  bin: "Waste Removal",
  hauling: "Waste Removal",

  supplier: "Supplier",
  suppliers: "Supplier",
  vendor: "Supplier",
  procurement: "Supplier",
  manufacturer: "Supplier",
};

module.exports = {
  TRADE_ALIASES,
};